version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_build:
      - sphinx-apidoc -o docs/source chainopy/ *.pyx

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_doc.txt
    - method: pip
      path: .
      extra_requirements:
        - build
        - docs

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

submodules:
  include: ['chainopy']
  recursive: true