version: 2

formats: 
  - htmlzip

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - python setup.py build_ext --inplace
  jobs:
    - sphinx-apidoc -o docs/source chainopy/

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_doc.txt
    - method: pip
      path: .
      extra_requirements:
        - build
        - docs

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

submodules:
  include: []
  recursive: true