version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_doc.txt
    - method: pip
      path: .
      extra_requirements:
        - build
        - docs

before_build:
  - - 'sphinx-apidoc -o docs/source chainopy/'


sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false