version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - python -m pip install -r requirements.txt
      - python -m pip install -r requirements_doc.txt
      - apt update -y
      - apt install -y pandoc
      - python -m pip install pandoc
      - python setup.py build_ext --inplace
      - sphinx-apidoc --private -o docs/source chainopy/

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_doc.txt
    - method: pip
      path: .
      extra_requirements:
        - build
        - docs

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

submodules:
  recursive: true
