name: ChainoPy Continuos Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install Package Dependencies
        run: pip install -r requirements.txt

      - name: Install Test Dependencies
        run: pip install -r requirements_test.txt

      - name: Build Cython Files
        run: python setup.py build_ext --inplace

      - name: Run Tests
        run: python -m pytest chainopy/tests/


  check-format:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{matrix.python-version}}

      - name: Install Black
        run: pip install black

      - name: Check Code Formatting
        run: black --check .

  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      
      - name: Set up pandoc
        run: sudo apt install pandoc

      - name: Install Doc dependencies
        run: pip install -r requirements_doc.txt

      - name: Install build dependencies
        run: pip install -r requirements.txt

      - name: Build Package
        run: python setup.py build_ext --inplace

      - name: Run apidoc
        run: sphinx-apidoc -o docs/source .

      - name: Build HTML documentation
        run: sphinx-build -b html docs/source docs/build/html
      
      - name: Navigate to docs build
        run: cd docs/build/html
