name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        with:
          package-dir: .
          output-dir: dist
          config-file: "./pyproject.toml"
          env:
            CIBW_ENVIRONMENT: sudo apt-get install python3-scipy

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl
          retention-days: 5

  download:
    runs-on: ubuntu-latest
    needs: build_wheels

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist/

    - name: List downloaded files
      run: ls -l dist/
